configuration:
  - Debug
  #- Release

environment:
  matrix:
    #- generator: "Visual Studio 14 2015"
    #- generator: "Visual Studio 14 2015 Win64"
    #- generator: "Visual Studio 10 2010"
    #- generator: "Visual Studio 10 2010 Win64"
    - generator: "MinGW Makefiles"

matrix:
  fast_finish: true
  
shallow_clone: true

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
before_build:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if "%generator%"=="MinGW Makefiles" set PATH=c:\MinGW\bin;%PATH%
  - cmake -Hsamples -Bbuild -G"%generator%" -DCMAKE_BUILD_TYPE=%configuration%

build_script:
  - cmake --build build
  
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))